version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-app
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  web:
    build: 
      context: .
    container_name: flask-app
    ports:
      - "8000:5000"
    networks:
      - app-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_APP=app.py

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: