name: test

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubunto-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1
      with:
        version: latest
    - name: Build and run Docker Compose
      run: |
        docker compose up --build -d
        sleep 20
    - name: Test and show logs
      run: |
        if ! curl --retry 10 --retry-connrefused http://localhost:8000/health; then
          echo "Test failed, showing logs:"
          docker compose logs
          exit 1
        fi
    - name: Clean up
      run: |
        docker compose down

      
