name: test

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1
      with:
        version: latest
    - name: Build and run Docker Compose
      run: |
        docker compose up --build -d
        sleep 20
    - name: Test and show logs
      run: |
        response=$(curl --retry 5 --retry-connrefused -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)
        if [ "$response" -ne 200 ]; then
          echo "Test failed: Expected HTTP 200 but got $response"
          echo "Showing logs:"
          docker compose logs
          exit 1
        fi
        echo "Test passed: /health returned HTTP 200"
      
    - name: Clean up
      run: |
        docker compose down

      
